package model;
// Generated Nov 14, 2018 3:30:41 PM by Hibernate Tools 4.3.1



/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer deptId;
     private Hod hod;
     private String deptName;

    public Department() {
    }

    public Department(Hod hod, String deptName) {
       this.hod = hod;
       this.deptName = deptName;
    }
   
    public Integer getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
    public Hod getHod() {
        return this.hod;
    }
    
    public void setHod(Hod hod) {
        this.hod = hod;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }




}


