package model;
// Generated Nov 14, 2018 3:30:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer logid;
     private String username;
     private String password;
     private String type;
     private Set hods = new HashSet(0);
     private Set staffs = new HashSet(0);

    public Login() {
    }

    public Login(String username, String password, String type, Set hods, Set staffs) {
       this.username = username;
       this.password = password;
       this.type = type;
       this.hods = hods;
       this.staffs = staffs;
    }
   
    public Integer getLogid() {
        return this.logid;
    }
    
    public void setLogid(Integer logid) {
        this.logid = logid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getHods() {
        return this.hods;
    }
    
    public void setHods(Set hods) {
        this.hods = hods;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


