package model;
// Generated Nov 14, 2018 3:30:41 PM by Hibernate Tools 4.3.1



/**
 * MeetingReply generated by hbm2java
 */
public class MeetingReply  implements java.io.Serializable {


     private Integer replyId;
     private Hod hod;
     private Meeting meeting;
     private String replyMessage;
     private String date;

    public MeetingReply() {
    }

    public MeetingReply(Hod hod, Meeting meeting, String replyMessage, String date) {
       this.hod = hod;
       this.meeting = meeting;
       this.replyMessage = replyMessage;
       this.date = date;
    }
   
    public Integer getReplyId() {
        return this.replyId;
    }
    
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }
    public Hod getHod() {
        return this.hod;
    }
    
    public void setHod(Hod hod) {
        this.hod = hod;
    }
    public Meeting getMeeting() {
        return this.meeting;
    }
    
    public void setMeeting(Meeting meeting) {
        this.meeting = meeting;
    }
    public String getReplyMessage() {
        return this.replyMessage;
    }
    
    public void setReplyMessage(String replyMessage) {
        this.replyMessage = replyMessage;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


