package model;
// Generated Nov 14, 2018 3:30:41 PM by Hibernate Tools 4.3.1



/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer staffId;
     private Hod hod;
     private Login login;
     private String fname;
     private String lname;
     private String phone;
     private String email;
     private String qualification;

    public Staff() {
    }

    public Staff(Hod hod, Login login, String fname, String lname, String phone, String email, String qualification) {
       this.hod = hod;
       this.login = login;
       this.fname = fname;
       this.lname = lname;
       this.phone = phone;
       this.email = email;
       this.qualification = qualification;
    }
   
    public Integer getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }
    public Hod getHod() {
        return this.hod;
    }
    
    public void setHod(Hod hod) {
        this.hod = hod;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }




}


